sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
script:
- npm run lint && npm run tests
notifications:
  slack: savichev95@gmail.com:dtrEmz259nh6SzVu2P38Lnnc
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key: 134bf008-8e37-471d-8b3c-1d1e0509e10d
  on: master
  app: dream-team-4
